// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC84MqhWOv9rxRJ4zDwiCx3qvbjbO5hlnM',
    appId: '1:630282730755:web:9b63d0402339b14107bd36',
    messagingSenderId: '630282730755',
    projectId: 'rex-super-app',
    authDomain: 'rex-super-app.firebaseapp.com',
    storageBucket: 'rex-super-app.appspot.com',
    measurementId: 'G-1LKFZE4VJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO3TwOJ9FmJrHvxE9fjSehJ1czDIEyvvw',
    appId: '1:630282730755:android:c30261b6071f398107bd36',
    messagingSenderId: '630282730755',
    projectId: 'rex-super-app',
    storageBucket: 'rex-super-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdOjKAJY37X8AZonL1OVMKak0IDZ-ueMA',
    appId: '1:630282730755:ios:8bc9b347ced1c4a107bd36',
    messagingSenderId: '630282730755',
    projectId: 'rex-super-app',
    storageBucket: 'rex-super-app.appspot.com',
    iosBundleId: 'com.rexmfb.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdOjKAJY37X8AZonL1OVMKak0IDZ-ueMA',
    appId: '1:630282730755:ios:8bc9b347ced1c4a107bd36',
    messagingSenderId: '630282730755',
    projectId: 'rex-super-app',
    storageBucket: 'rex-super-app.appspot.com',
    iosBundleId: 'com.rexmfb.mobile',
  );
}
